# --- !Ups

CREATE TABLE IF NOT EXISTS Profile (
	ProfileId INT NOT NULL AUTO_INCREMENT,
	Email VARCHAR(64) NOT NULL,
	Password CHAR(177) NOT NULL,
	PasswordExpired BIT NOT NULL DEFAULT 0,
	DateCreated DATETIME NOT NULL DEFAULT NOW(),
	LastLoginDate DATETIME NOT NULL DEFAULT NOW(),

	CONSTRAINT PK_Profile PRIMARY KEY (ProfileId),
	CONSTRAINT UQ_Profile_Email UNIQUE (Email)
);

CREATE TABLE IF NOT EXISTS News (
	NewsId INT NOT NULL AUTO_INCREMENT,
	Subject VARCHAR(255) NOT NULL,
	DateCreated DATETIME NOT NULL DEFAULT NOW(),
	DateModified DATETIME NOT NULL DEFAULT NOW(),
	PostedByProfileId INT NOT NULL,
	Content TEXT NOT NULL,

	CONSTRAINT PK_News PRIMARY KEY (NewsId),
	CONSTRAINT FK_News_Profile FOREIGN KEY (PostedByProfileId) REFERENCES Profile(ProfileId)
);
