# --- !Ups
ALTER TABLE GameResult DROP COLUMN Kills;
ALTER TABLE GameResult DROP COLUMN Returns;
ALTER TABLE GameResult ADD COLUMN PCaptures INT NOT NULL DEFAULT 0 AFTER Captures;
ALTER TABLE GameResult ADD COLUMN Drops INT NOT NULL DEFAULT 0 AFTER PCaptures;
ALTER TABLE GameResult ADD COLUMN Frags INT NOT NULL DEFAULT 0 AFTER Drops;

# --- !Downs
ALTER TABLE GameResult ADD COLUMN Kills INT NOT NULL DEFAULT 0 AFTER Deaths;
ALTER TABLE GameResult ADD COLUMN Returns INT NOT NULL DEFAULT 0 AFTER Kills;
ALTER TABLE GameResult DROP COLUMN PCaptures;
ALTER TABLE GameResult DROP COLUMN Drops;
ALTER TABLE GameResult DROP COLUMN Frags;
