# --- !Ups

ALTER TABLE TeamPlayer MODIFY IsCaptain TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE Player MODIFY IsActive TINYINT(1) NOT NULL DEFAULT 1;
ALTER TABLE Profile MODIFY PasswordExpired TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE Team MODIFY IsActive TINYINT(1) NOT NULL DEFAULT 1;

# --- !Downs

ALTER TABLE TeamPlayer MODIFY IsCaptain BIT(1) NOT NULL DEFAULT b'0';
ALTER TABLE Player MODIFY IsActive BIT(1) NOT NULL DEFAULT b'1';
ALTER TABLE Profile MODIFY PasswordExpired BIT(1) NOT NULL DEFAULT b'0';
ALTER TABLE Team MODIFY IsActive BIT(1) NOT NULL DEFAULT b'1';

