# --- !Ups

CREATE TABLE IF NOT EXISTS Team (
	TeamId INT NOT NULL AUTO_INCREMENT,
	Name VARCHAR(48) NOT NULL,
	IsActive BIT NOT NULL DEFAULT 0,

	CONSTRAINT PK_Team PRIMARY KEY (TeamId),
	CONSTRAINT UQ_Team_Name UNIQUE (Name)
) ENGINE = INNODB;

CREATE TABLE IF NOT EXISTS Player (
	PlayerId INT NOT NULL AUTO_INCREMENT,
	Name VARCHAR(48) NOT NULL,
	IsActive BIT NOT NULL DEFAULT 0,

	CONSTRAINT PK_Player PRIMARY KEY (PlayerId),
	CONSTRAINT UQ_Player_Name UNIQUE (Name)
) ENGINE = INNODB;

CREATE TABLE IF NOT EXISTS TeamPlayer (
	TeamId INT NOT NULL,
	PlayerId INT NOT NULL,
	SeasonId INT NOT NULL,
	IsCaptain BIT NOT NULL DEFAULT 0,

	CONSTRAINT PK_TeamPlayer PRIMARY KEY (TeamId, PlayerId, SeasonId),
	CONSTRAINT FK_TeamPlayer_Team FOREIGN KEY (TeamId) REFERENCES Team(TeamId),
	CONSTRAINT FK_TeamPlayer_Player FOREIGN KEY (PlayerId) REFERENCES Player(PlayerId),
	CONSTRAINT FK_TeamPlayer_Season FOREIGN KEY (SeasonId) REFERENCES Season(SeasonId)
) ENGINE = INNODB;
