# --- !Ups

CREATE TABLE IF NOT EXISTS Week (
	WeekId INT NOT NULL,
	Name VARCHAR(16) NOT NULL,

	CONSTRAINT PK_Week PRIMARY KEY(WeekId),
	CONSTRAINT UQ_Week_Name UNIQUE (Name)
) ENGINE = INNODB;

CREATE TABLE IF NOT EXISTS Game (
	GameId INT NOT NULL AUTO_INCREMENT,
	WeekId INT NOT NULL,
	SeasonId INT NOT NULL,
	ScheduledPlayTime DATETIME NOT NULL,

	CONSTRAINT PK_Game PRIMARY KEY (GameId),
	CONSTRAINT FK_Game_Week FOREIGN KEY (WeekId) REFERENCES Week(WeekId),
	CONSTRAINT FK_Game_SeasonId FOREIGN KEY (SeasonId) REFERENCES Season(SeasonId)
) ENGINE = INNODB;

CREATE TABLE IF NOT EXISTS TeamGame (
	GameId INT NOT NULL,
	Team1Id INT NOT NULL,
	Team2Id INT NOT NULL,

	CONSTRAINT PK_TeamGame PRIMARY KEY (GameId, Team1Id, Team2Id),
	CONSTRAINT FK_TeamGame_Game FOREIGN KEY (GameId) REFERENCES Game(GameId),
	CONSTRAINT FK_TeamGame_Team_1 FOREIGN KEY (Team1Id) REFERENCES Team(TeamId),
	CONSTRAINT FK_TeamGame_Team_2 FOREIGN KEY (Team2Id) REFERENCES Team(TeamId)
) ENGINE = INNODB;

CREATE TABLE IF NOT EXISTS GameResult (
	GameResultId INT NOT NULL AUTO_INCREMENT,
	GameId INT NOT NULL,
	PlayerId INT NOT NULL,
	Captures INT NOT NULL DEFAULT 0,
	Returns INT NOT NULL DEFAULT 0,
	Kills INT NOT NULL DEFAULT 0,
	Deaths INT NOT NULL DEFAULT 0,

	CONSTRAINT PK_GameResult PRIMARY KEY (GameResultId),
	CONSTRAINT FK_GameResult_Game FOREIGN KEY (GameId) REFERENCES Game(GameId),
	CONSTRAINT FK_GameResult_Player FOREIGN KEY (PlayerId) REFERENCES Player(PlayerId)
) ENGINE = INNODB;

CREATE TABLE IF NOT EXISTS GameDemo (
	GameDemoId INT NOT NULL AUTO_INCREMENT,
	GameId INT NOT NULL,
	PlayerId INT NOT NULL,
	Filename VARCHAR(255) NOT NULL,
	DateUploaded TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	DemoFile MEDIUMBLOB NOT NULL,

	CONSTRAINT FK_GameDemo_Game FOREIGN KEY (GameId) REFERENCES Game(GameId),
	CONSTRAINT FK_GameDemo_Player FOREIGN KEY (PlayerId) REFERENCES Player(PlayerId)
) ENGINE = INNODB;

# --- !Downs

DROP TABLE GameDemo;
DROP TABLE GameResult;
DROP TABLE TeamGame;
DROP TABLE Game;
DROP TABLE Week;
