package components

import data._
import services._

trait ProfileRegistry
extends ProfileServiceComponent
with ProfileRepositoryComponent

trait ProfileComponentImpl
extends ProfileRegistry
with ProfileServiceComponentImpl
with ProfileRepositoryComponentImpl

trait NewsRegistry
extends NewsServiceComponent
with NewsRepositoryComponent

trait NewsComponentImpl
extends NewsRegistry
with NewsServiceComponentImpl
with NewsRepositoryComponentImpl
