package components

import data._
import services._

trait PlayerRegistry
extends PlayerServiceComponent
with PlayerRepositoryComponent
with TeamRepositoryComponent

trait PlayerComponentImpl
extends PlayerRegistry
with PlayerServiceComponentImpl
with PlayerRepositoryComponentImpl